apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: api
    spec:
      containers:
        - env:
            - name: APP_DB_BASE
              valueFrom:
                configMapKeyRef:
                  key: APP_DB_BASE
                  name: env
            - name: APP_DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: APP_DB_HOST
                  name: env
            - name: APP_DB_PASS
              valueFrom:
                configMapKeyRef:
                  key: APP_DB_PASS
                  name: env
            - name: APP_DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: APP_DB_PORT
                  name: env
            - name: APP_DB_USER
              valueFrom:
                configMapKeyRef:
                  key: APP_DB_USER
                  name: env
            - name: APP_ENABLE_TASKIQ
              valueFrom:
                configMapKeyRef:
                  key: APP_ENABLE_TASKIQ
                  name: env
            - name: APP_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  key: APP_ENVIRONMENT
                  name: env
            - name: APP_HOST
              value: 0.0.0.0
            - name: APP_RABBIT_HOST
              valueFrom:
                configMapKeyRef:
                  key: APP_RABBIT_HOST
                  name: env
            - name: APP_RABBIT_PASS
              valueFrom:
                configMapKeyRef:
                  key: APP_RABBIT_PASS
                  name: env
            - name: APP_RABBIT_PORT
              valueFrom:
                configMapKeyRef:
                  key: APP_RABBIT_PORT
                  name: env
            - name: APP_RABBIT_USER
              valueFrom:
                configMapKeyRef:
                  key: APP_RABBIT_USER
                  name: env
            - name: APP_RABBIT_VHOST
              valueFrom:
                configMapKeyRef:
                  key: APP_RABBIT_VHOST
                  name: env
            - name: APP_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  key: APP_REDIS_HOST
                  name: env
            - name: APP_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  key: APP_REDIS_PORT
                  name: env
            - name: APP_RELOAD
              valueFrom:
                configMapKeyRef:
                  key: APP_RELOAD
                  name: env
            - name: APP_WORKERS_COUNT
              valueFrom:
                configMapKeyRef:
                  key: APP_WORKERS_COUNT
                  name: env
          image: app:latest
          name: api
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
