apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: migrator
  name: migrator
spec:
  containers:
    - args:
        - piccolo
        - migrations
        - forwards
        - all
      env:
        - name: PICCOLO_CONF
          value: app.piccolo_conf
        - name: app_DB_BASE
          value: app
        - name: app_DB_HOST
          value: app-db
        - name: app_DB_PASS
          value: app
        - name: app_DB_PORT
          value: "5432"
        - name: app_DB_USER
          value: app
      image: app:latest
      name: migrator
  restartPolicy: Never
